table entrees {
    id int [pk]
    name varchar
    price int
}

table vegetables {
    id int [pk]
    type varchar
    price int
}

table sides {
    id int [pk]
    title varchar
    price int 
}

table orders {
    id int [pk]
    entreeId int [ref: > entrees.id]
    vegetablesId int [ref: > vegetables.id]
    sidesId int [ref: > sides.id]
}